### ISSUE TITLE
getting error while starting

### ISSUE THREAD

**Issue by Vishal-Marvel** [kilmajster/ngrok-spring-boot-starter#67]
Exception in thread "ngrok-thread-1" java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'
	at ngrok.api.NgrokApiClient.lambda$isResponding$bfb15c2f$1(NgrokApiClient.java:188)
	at io.vavr.control.Try.of(Try.java:75)
	at ngrok.api.NgrokApiClient.isResponding(NgrokApiClient.java:184)
	at ngrok.NgrokRunner.ngrokIsNotRunning(NgrokRunner.java:121)
	at ngrok.NgrokRunner.lambda$run$0(NgrokRunner.java:50)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kilmajster** [comment]
Hi @Vishal-Marvel, thank you for reporting the issue, can you please provide some more details about the environment you are using? Version of java, Spring?
