### ISSUE TITLE
Extracting downloaded ngrok throws EOFException

### ISSUE THREAD

**Issue by KaurKadakWise** [kilmajster/ngrok-spring-boot-starter#70]
Getting this error on startup when trying to extract downloaded ngrok

Exception in thread "ngrok-thread-1" java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
        at ngrok.download.NgrokFileExtractUtils.extractZip(NgrokFileExtractUtils.java:109)
        at ngrok.download.NgrokFileExtractUtils.extractArchive(NgrokFileExtractUtils.java:36)
        at ngrok.download.NgrokDownloader.downloadAndExtractNgrokTo(NgrokDownloader.java:30)
        at ngrok.NgrokRunner.downloadAndExtractNgrokBinary(NgrokRunner.java:107)
        at ngrok.NgrokRunner.lambda$run$0(NgrokRunner.java:52)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:266)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:412)
        at ngrok.download.NgrokFileExtractUtils.extractFile(NgrokFileExtractUtils.java:127)
        at ngrok.download.NgrokFileExtractUtils.extractZip(NgrokFileExtractUtils.java:104)

**Comment by kilmajster** [comment]
Hi @KaurKadakWise, thank you for reporting this. Can you provide some more specifics, eg. which version of this starter you're using or any other things that can help me to reproduce yours issue?

**Comment by KaurKadakWise** [comment]
ngrok-spring-boot-starter version -> 0.9.0
Spring boot version -> 3.1.8

didn't delve too deep onto why it was happening, defaulted with running ngrok locally on my terminal
